name: PHP code quality

on:
  push:
  pull_request:

jobs:
  static:
    name: Static code analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: '8.2'
        tools: composer
        extensions: dom, simplexml

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      run: composer install --no-interaction --no-progress

    - name: Run PHPStan
      run: composer analyse

  test:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: xdebug
        extensions: dom, simplexml

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      run: composer install --no-interaction --no-progress

    - name: Run test suite
      run: composer test